### ISSUE TITLE
Issue with linker when calling from python

### ISSUE THREAD

**Issue by ASKabalan** [NVIDIA/cuDecomp#14]
Hello,

I am trying to port and bind this library in Python
I was able to build it then link it to my library and use it from the library (Project is here : [JaxDecomp](https://github.com/DifferentiableUniverseInitiative/jaxDecomp) )

But when I call it from Python via pybind11,  I get this weird link error 

`cuDecomp/build/lib/libcudecomp.so: undefined symbol: __sync_val_compare_and_swap_4`

I have tried to link `libstdc++` , ` libatomic`, and  `libgcc_s` but nothing happend.

Do you have any idea why I am getting this error?

**Comment by EiffL** [comment]
Hi @ASKabalan :-) Most likely it comes from an issue with the compiler chain you are using note being consistent between the compilation of cuDecomp and the next step of bindings used with pybind. 

Can you verify that you can run for instance this one once you have compiled cuDecomp?
https://github.com/NVIDIA/cuDecomp/blob/e364ed5d872b7ff9a9e181ba667b998eb7a8174f/tests/cc/transpose_test.cc 

If so, then I don't think it's a cuDecomp issue, and we can move the discussion to the JaxDecomp repo to go more into the details of the steps you are following to compile the bindings.

**Comment by ASKabalan** [comment]
The tests all run.
I am gonna explore the inconsistency between pybind and the cuDecomp compilations
