### ISSUE TITLE
Question about packaging

### ISSUE THREAD

**Issue by ASKabalan** [NVIDIA/cuDecomp#32]
Hello cuDecomp team.

I am looking to package [jaxDecomp](https://github.com/DifferentiableUniverseInitiative/jaxDecomp)  into a pypi package (I am currently using cuDecomp as a CMake subdirectory)

Are you ok with me packaging the code or/and the binary of cuDecomp?

Thank you.

**Comment by romerojosh** [comment]
Hi @ASKabalan,
Glad to see you are making progress on jaxDecomp and congrats on the upcoming release! 

NVIDIA does not provide legal guidance, but our intention with the selected [license](https://github.com/NVIDIA/cuDecomp/blob/main/LICENSE) is to foster broad use. You must ensure your use is consistent with the license terms.

**Comment by ASKabalan** [comment]
Thank you @romerojosh .
It is consistent with the MIT license that we are using
