### ISSUE TITLE
Need help building library

### ISSUE THREAD

**Issue by ShatrovOA** [NVIDIA/cuDecomp#39]
Hello everyone.

I am trying to build library, but have not success.
HPC SDK Version

```bash
nvc++ --version

nvc++ 24.5-0 64-bit target on x86-64 Linux -tp broadwell 
NVIDIA Compilers and Tools
Copyright (c) 2024, NVIDIA CORPORATION & AFFILIATES.  All rights reserved
```

Linux
```bash
cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

CMake
```bash
cmake --version

cmake version 3.29.0
```

Running Cmake
```bash
cmake -DNVHPC_CUDA_VERSION=11.8 -DCUDECOMP_ENABLE_NVSHMEM=on -DCUDECOMP_BUILD_EXTRAS=on ..

-- The CXX compiler identification is NVHPC 24.5.0
-- The CUDA compiler identification is NVIDIA 11.8.89
-- The Fortran compiler identification is NVHPC 24.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: $HOMEDIR/hpc_sdk/Linux_x86_64/24.5/compilers/bin/nvc++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: $HOMEDIR/hpc_sdk/Linux_x86_64/24.5/cuda/11.8/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: $HOMEDIR/hpc_sdk/Linux_x86_64/24.5/compilers/bin/nvfortran - skipped
-- Found MPI_CXX: $HOMEDIR/hpc_sdk/Linux_x86_64/24.5/comm_libs/11.8/openmpi4/openmpi-4.1.5/lib/libmpi.so (found version "3.1")
-- Found MPI_Fortran: $HOMEDIR/hpc_sdk/Linux_x86_64/24.5/comm_libs/11.8/openmpi4/openmpi-4.1.5/lib/libmpi_usempif08.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- CUDA version selected: 11.8
-- NVHPC_MATH_LIBRARY_DIR = $HOMEDIR/hpc_sdk/Linux_x86_64/24.5/cmake/../math_libs/11.8/lib64
-- CUDA version selected: 11.8
-- Using NCCL library: $HOMEDIR/hpc_sdk/Linux_x86_64/24.5/comm_libs/11.8/nccl/lib/libnccl.so
-- CUDA version selected: 11.8
-- Using NVSHMEM installation at: $HOMEDIR/hpc_sdk/Linux_x86_64/24.5/cmake/../comm_libs/11.8/nvshmem/lib
-- Configuring done (13.9s)
-- Generating done (0.6s)
-- Build files have been written to: $HOMEDIR/cuDecomp/build
```

Running make
```bash
make

[  1%] Building CXX object CMakeFiles/cudecomp.dir/src/autotune.cc.o
"$HOMEDIR/hpc_sdk/Linux_x86_64/24.5/cmake/../cuda/11.8/include/cuda/std/detail/libcxx/include/cmath", line 323: error: the global scope has no "signbit"
  using ::signbit;
          ^

"$HOMEDIR/hpc_sdk/Linux_x86_64/24.5/cmake/../cuda/11.8/include/cuda/std/detail/libcxx/include/cmath", line 324: error: the global scope has no "isfinite"
  using ::isfinite;
          ^

2 errors detected in the compilation of "$HOMEDIR/cuDecomp/src/autotune.cc".
```

Can you help me understand what am I doing wrong?
Thanks!

**Comment by romerojosh** [comment]
This issue arises due to incompabilities with `libcudacxx` and old versions of GCC. What version of GCC is installed on your system?
You will likely need to update GCC on your system, or update to a newer OS to use cuDecomp.

**Comment by ShatrovOA** [comment]
Globally installed GCC is 4.8.5
But there are newer versions available in custom directory. 
10.4.0
11.3.0
12.2.0
7.3

Is there any way to use them instead of globally installed?

**Comment by romerojosh** [comment]
The tricky thing here is that the NVHPC compilers will configure themselves (including setting which GCC toolchain to use) at install time. Your options are:
1. Reinstall the NVHPC SDK, ensuring that the GCC you want to use is the one loaded in your path, or
2. Set up a "local rc" file for the compilers to use to override the GCC version at runtime (https://docs.nvidia.com/hpc-sdk/archive/24.9/compilers/hpc-compilers-user-guide/index.html#site-spec-comp-cust). I'm asking some team members what exactly the recipe to do this correctly is since the documentation I linked is a bit sparse. I will follow up with more detail there.

Otherwise, I'd highly recommend updating your operating system. Outside of the libcudacxx issues, CentOS 7 is no longer supported by NVHPC compilers after 24.7.

**Comment by romerojosh** [comment]
For the local rc file option, you can try something like the following:
```
${NVHPC_ROOT}/compilers/bin/makelocalrc -gcc <path to the GCC you want to use> -n ${NVHPC_ROOT}/compilers/bin > ${HOME}/.mynvc++rc
```
After this, try re-running CMake and compiling again.

**Comment by ShatrovOA** [comment]
> For the local rc file option, you can try something like the following:
> 
> ```
> ${NVHPC_ROOT}/compilers/bin/makelocalrc -gcc <path to the GCC you want to use> -n ${NVHPC_ROOT}/compilers/bin > ${HOME}/.mynvc++rc
> ```
> 
> After this, try re-running CMake and compiling again.

This does work. Thank you.
Also I do believe that updating operating system or globally installed GCC is unrealistic.

**Comment by romerojosh** [comment]
Glad to hear the local rc trick worked for you! Thanks for the feedback and feel free to open up any other issues you run into with the library.
