### ISSUE TITLE
Missing MPI import in `cudecomp.h`

### ISSUE THREAD

**Issue by EiffL** [NVIDIA/cuDecomp#9]
Following the removal of MPI, cutensor, and NCCL imports at the top of cudecomp.h in [this commit
](https://github.com/NVIDIA/cuDecomp/commit/df430e7158eaee8485830e404645e32d16f321cc) there is now an undefined reference to  `MPI_Comm` at this line of the include file:
https://github.com/NVIDIA/cuDecomp/blob/e0cf8713074739bbb057c058d0a386c217a73eeb/include/cudecomp.h#L186

This is a bit awkward because it forces the user to import manually MPI even in files that do not need to call the init function.  Could it be possible to add back that MPI import?

**Comment by romerojosh** [comment]
Good catch @EiffL! I was a bit overzealous removing unnecessary includes from the `cudecomp.h` header. The include was added back in #10. Thanks for reporting!
